logging:
  path: ./log/
  level:
    org:
      springframework:
#        web: debug
spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
server:
  port: 8082
  tomcat:
    uri-encoding: utf-8
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
sso:
  redis:
    address: redis://myRedis:123456@120.79.79.151:6379
    expire:
      minite: 1440
