zuul:
  routes:
    # /myProduct/product/list -> /product/product/list
    aaaaaa:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
  #简洁写法
  #    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false
server:
  port: 9000
spring:
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
