logging:
  path: ./logs/
spring:
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
server:
  port: 8085
  tomcat:
    uri-encoding: utf-8
redis:
  address: redis://myRedis:123456@120.79.79.151:6379
