logging:
  path: ./logs/
spring:
  data:
    mongodb:
      uri: mongodb://DocTool:123456@120.79.79.151:27017/DocTool?maxPoolSize=50&connectTimeoutMS=30000&socketTimeoutMS=3000
  rabbitmq:
    host: 120.79.79.151
    port: 5672
    username: guest
    password: guest
  zipkin:
    base-url: http://120.79.79.151:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
server:
  port: 8083
  tomcat:
    uri-encoding: utf-8

#定时任务线程池配置
schedule:
  threadpool:
    corePoolSize: 10
    maxPoolSize: 200
    queueCapacity: 10
websocket:
  MaxTextMessageBufferSize: 8192
  MaxBinaryMessageBufferSize: 8192
redis:
  address: redis://myRedis:123456@120.79.79.151:6379
